install.packages("dplyr") 
library(dplyr)
dat <- read.csv("us-states.csv")

## ALABAMA TOTAL DEATHS
AL <- filter(dat, state == "Alabama") %>% select(deaths)
ALtotal <- sum(AL)

## ALASKA TOTAL DEATHS
AK <- filter(dat, state == "Alaska") %>% select(deaths)
AKtotal <- sum(AK)

## ARIZONA TOTAL DEATHS
AZ <- filter(dat, state == "Arizona") %>% select(deaths)
AZtotal <- sum(AZ)

## ARKANSAS TOTAL DEATHS
AR <- filter(dat, state == "Arkansas") %>% select(deaths)
ARtotal <- sum(AR)

## CALIFORNIA TOTAL DEATHS
## COLORADO TOTAL DEATHS
## CONNECTICUT TOTAL DEATHS
## DELAWARE TOTAL DEATHS
## FLORIDA TOTAL DEATHS
## GEORGIA TOTAL DEATHS
## HAWAII TOTAL DEATHS
## IDAHO TOTAL DEATHS
## ILLINOIS TOTAL DEATHS
## INDIANA TOTAL DEATHS
## IOWA TOTAL DEATHS
## KANSAS TOTAL DEATHS
## KENTUCKY TOTAL DEATHS
## LOUISINANA TOTAL DEATHS
## MAINE TOTAL DEATHS
## MARYLAND TOTAL DEATHS
## MASSACHUSETTS TOTAL DEATHS
## MICHIGAN TOTAL DEATHS
## MINNESOTA TOTAL DEATHS
## MISSISSIPPI TOTAL DEATHS
## MISSOURI TOTAL DEATHS
## MONTANA TOTAL DEATHS
## NEBRASKA TOTAL DEATHS
## NEVADA TOTAL DEATHS
## NEW HAMPSHIRE TOTAL DEATHS
## NEW JERSEY TOTAL DEATHS
## NEW MEXICO TOTAL DEATHS
## NEW YORK TOTAL DEATHS
## NORTH CAROLINA TOTAL DEATHS
## NORTH DAKOTA TOTAL DEATHS
## OHIO TOTAL DEATHS
## OKLAHOMA TOTAL DEATHS
## OREGON TOTAL DEATHS
## PENNSYLVANIA TOTAL DEATHS
## RHODE ISLAND TOTAL DEATHS
## SOUTH CAROLINA TOTAL DEATHS
## SOUTH DAKOTA TOTAL DEATHS
## TENNESSEE TOTAL DEATHS
## TEXAS TOTAL DEATHS
## UTAH TOTAL DEATHS
## VERMONT TOTAL DEATHS
## VIRGINIA TOTAL DEATHS

## WASHINGTON TOTAL DEATHS
WA <- filter(dat, state == "Washington") %>% select(deaths)
WAtotal <- sum(WA)

## WEST VIRGINIA TOTAL DEATHS
## WISCONSIN TOTAL DEATHS
## WYOMING TOTAL DEATHS
